apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cpcms-portal-admin-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/staocubee/my-app.git
    targetRevision: main
    path: chart
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: my-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true