apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: promtail
    targetRevision: 6.16.6
    helm:
      values: |
        fullnameOverride: promtail

        daemonset:
          enabled: true

        deployment:
          enabled: false

        defaultVolumes:
          - name: pods
            hostPath:
              path: /var/log/pods

        defaultVolumeMounts:
          - name: pods
            mountPath: /var/log/pods
            readOnly: true

        config:
          positions:
            filename: /tmp/positions.yaml
          clients:
            - url: http://loki.logging.svc.cluster.local:3100/loki/api/v1/push
          snippets:
            scrapeConfigs: |
              - job_name: kubernetes-pods
                pipeline_stages:
                  - cri: {}
                kubernetes_sd_configs:
                  - role: pod
                relabel_configs:
                  - source_labels:
                      - __meta_kubernetes_pod_node_name
                    target_label: __host__
                  - action: labelmap
                    regex: __meta_kubernetes_pod_label_(.+)
                  - action: replace
                    source_labels:
                      - __meta_kubernetes_namespace
                    target_label: namespace
                  - action: replace
                    source_labels:
                      - __meta_kubernetes_pod_name
                    target_label: pod
                  - action: replace
                    source_labels:
                      - __meta_kubernetes_pod_container_name
                    target_label: container
                  - replacement: /var/log/pods/*$1/*.log
                    separator: /
                    source_labels:
                      - __meta_kubernetes_pod_uid
                      - __meta_kubernetes_pod_container_name
                    target_label: __path__

        resources:
          requests:
            cpu: 50m
            memory: 64Mi
            ephemeral-storage: 512Mi
          limits:
            memory: 128Mi
            ephemeral-storage: 512Mi

  destination:
    server: https://kubernetes.default.svc
    namespace: logging

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true