apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default

  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/spec/containers/0/resources
        - /spec/template/spec/initContainers/0/resources
        - /spec/template/spec/tolerations

  source:
    repoURL: https://strimzi.io/charts/
    chart: strimzi-kafka-operator
    targetRevision: 0.45.0
    helm:
      values: |
        watchAnyNamespace: false
        watchNamespaces:
          - kafka
          - strimzi-system

        replicas: 1

        resources:
          requests:
            cpu: 250m
            memory: 512Mi
            ephemeral-storage: 1Gi
          limits:
            memory: 768Mi
            ephemeral-storage: 1Gi

        livenessProbe:
          initialDelaySeconds: 60
          timeoutSeconds: 5
          periodSeconds: 30
          failureThreshold: 6

        readinessProbe:
          initialDelaySeconds: 60
          timeoutSeconds: 5
          periodSeconds: 30
          failureThreshold: 6

  destination:
    server: https://kubernetes.default.svc
    namespace: strimzi-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true