apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-cert
  namespace: istio-ingress
spec:
  secretName: argocd-tls
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  commonName: 34.170.137.139.nip.io
  dnsNames:
    - 34.170.137.139.nip.io
    - "argocd.34.170.137.139.nip.io"
    - "grafana.34.170.137.139.nip.io"
    - "nexus.34.170.137.139.nip.io"
    - "dev-es-es-http.34.170.137.139.nip.io"
    - "dev-kibana-kb-http.34.170.137.139.nip.io"
    - "elastic-operator-webhook.34.170.137.139.nip.io"
    - "monitoring-kube-prometheus-prometheus.34.170.137.139.nip.io"
    - "monitoring-kube-prometheus-alertmanager.34.170.137.139.nip.io"
