apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-cert
  namespace: istio-ingress
spec:
  secretName: argocd-tls
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  commonName: 136.113.23.157.nip.io
  dnsNames:
    - 136.113.23.157.nip.io
    - argocd.136.113.23.157.nip.io
    - grafana.136.113.23.157.nip.io
    - nexus.136.113.23.157.nip.io
