apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: platform-routing
  namespace: istio-system
spec:
  hosts:
    - "argocd.34.170.137.139.nip.io"
    - "grafana.34.170.137.139.nip.io"
    - "nexus.34.170.137.139.nip.io"
    - "dev-es-es-http.34.170.137.139.nip.io"
    - "dev-kibana-kb-http.34.170.137.139.nip.io"
    - "elastic-operator-webhook.34.170.137.139.nip.io"
    - "monitoring-kube-prometheus-prometheus.34.170.137.139.nip.io"
    - "monitoring-kube-prometheus-alertmanager.34.170.137.139.nip.io"


    
  gateways:
    - istio-system/platform-gateway
  http:
    # 1. ArgoCD Route
    - match:
        - headers:
            host:
              exact: "argocd.34.170.137.139.nip.io"
      route:
        - destination:
            host: argocd-server.argocd.svc.cluster.local
            port:
              number: 80

    # 2. Grafana Route
    - match:
        - headers:
            host:
              exact: "grafana.34.170.137.139.nip.io"
      route:
        - destination:
            host: monitoring-grafana.monitoring.svc.cluster.local
            port:
              number: 80

    # 3. Nexus Route
    - match:
        - headers:
            host:
              exact: "nexus.34.170.137.139.nip.io"
      route:
        - destination:
            host: nexus-nexus-repository-manager.nexus.svc.cluster.local
            port:
              number: 8081

    # 4. Elastic Route
    - match:
        - headers:
            host:
              exact: "dev-es-es-http.34.170.137.139.nip.io"
      route:
        - destination:
            host: dev-es-es-http.elastic.svc.cluster.local
            port:
              number: 9200

    # 5. Kibana Route
    - match:
        - headers:
            host:
              exact: "dev-kibana-kb-http.34.170.137.139.nip.io"
      route:
        - destination:
            host: dev-kibana-kb-http.elastic.svc.cluster.local
            port:
              number: 5601

    # 5. Elastic Operator Route
    - match:
        - headers:
            host:
              exact: "elastic-operator-webhook.34.170.137.139.nip.io"
      route:
        - destination:
            host: elastic-operator-webhook.elastic.svc.cluster.local
            port:
              number: 9443

    # 5. Monitoring Prometheus Operator Route
    - match:
        - headers:
            host:
              exact: "monitoring-kube-prometheus-prometheus.34.170.137.139.nip.io"
      route:
        - destination:
            host: monitoring-kube-prometheus-prometheus.monitoring.svc.cluster.local
            port:
              number: 9090

    # 5. Monitoring Prometheus Alertmanager Route
    - match:
        - headers:
            host:
              exact: "monitoring-kube-prometheus-alertmanager.34.170.137.139.nip.io"
      route:
        - destination:
            host: monitoring-kube-prometheus-alertmanager.monitoring.svc.cluster.local
            port:
              number: 9093