apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: argocd
spec:
  hosts:
  - "platform.34.63.239.83.nip.io"
  gateways:
  - istio-system/platform-gateway
  http:
  - match:
    - uri:
        prefix: /argocd
    rewrite:
      uri: /
    route:
    - destination:
        host: argocd-server.argocd.svc.cluster.local
        port:
          number: 80
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: grafana
spec:
  hosts:
  - "platform.34.63.239.83.nip.io"
  gateways:
  - istio-system/platform-gateway
  http:
  - match:
    - uri:
        prefix: /grafana
    rewrite:
      uri: /
    route:
    - destination:
        host: kube-prometheus-stack-grafana.monitoring.svc.cluster.local
        port:
          number: 80

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: nexus
spec:
  hosts:
  - "platform.34.63.239.83.nip.io"
  gateways:
  - istio-system/platform-gateway
  http:
  - match:
    - uri:
        prefix: /nexus
    rewrite:
      uri: /
    route:
    - destination:
        host: nexus.nexus.svc.cluster.local
        port:
          number: 80