apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd-install.yaml

namespace: argocd


patches:
  - target:
      kind: ConfigMap
      name: argocd-cm
    patch: |-
      - op: replace
        path: /data/url
        value: "https://argocd.136.115.108.14.nip.io"